from typing import ClassVar


class Queenconfig:

    """

    Configuration class generated by Queenconf

    """

    def __init__(self):

        self.config = Config()


class Config:
    """
    Configuration class generated by Queenconf
    """
    def __init__(self):
        pass

 
