from typing import ClassVar


class Queenconfig:

    """

    Configuration class generated by Queenconf

    """

    def __init__(self):

        self.config = Config()


class Admin:
    def __init__(self):
        pass

    adminPageIconName: ClassVar[str] = 'user'
class Laywer:
    def __init__(self):
        pass

    codeOfConductContent: ClassVar[str] = 'Every participant has to....'
    extraPageTitle: ClassVar[str] = '""'
class Config:
    def __init__(self):
        pass

    showExtraHeader: ClassVar[bool] = True
    rowsPerPage: ClassVar[int] = 4
    userMenuVisible: ClassVar[bool] = False
    showBlackFridayBanner: ClassVar[bool] = True
    admin: ClassVar[class] = Admin()
    laywer: ClassVar[class] = Laywer()

