from typing import ClassVar


class Queenconfig:

    """

    Configuration class generated by Queenconf

    """

    def __init__(self):

        self.config = Config()


class Leaf0:
    def __init__(self):
        pass

class Leaf1:
    def __init__(self):
        pass

    adminButtonSaveSettingsText: ClassVar[str] = '"Save Settings"'
    showOrHideGearIcon: ClassVar[bool] = True
class Leaf2:
    def __init__(self):
        pass

class Config:
    def __init__(self):
        pass

    leaf0: ClassVar[class] = Leaf0()
    leaf1: ClassVar[class] = Leaf1()
    leaf2: ClassVar[class] = Leaf2()
    leaf3: ClassVar[str] = 'aasdfasdfasdfasdfasdfdfasdfadsfasdfasdfasdfadsfadsfasdfadsfaw23423432324sdfasdfadsfasdf   sadfsdfsd asdfsdf asdfasdfasdfasdfasdfasdfa   sdfasdfasdfadsfasdfadsfsdf'

