from typing import ClassVar


class Queenconfig:

    """

    Configuration class generated by Queenconf

    """

    def __init__(self):

        self.config = Config()


class Admin:
    def __init__(self):
        pass

    adminPageIconName: ClassVar[str] = 'user'
 class Config:
    def __init__(self):
        pass

    showExtraHeader: ClassVar[bool] = True
    rowsPerPage: ClassVar[int] = 5
    userMenuVisible: ClassVar[bool] = False
    showBlackFridayBanner: ClassVar[bool] = False
    admin: ClassVar[class] = Admin()
 
