from typing import ClassVar


class Queenconfig:

    """

    Configuration class generated by Queenconf

    """

    def __init__(self):

        self.config = Config()


class Leaf_0:
    """
    Configuration class generated by Queenconf
    """
    def __init__(self):
        pass

 class Leaf_1:
    """
    Configuration class generated by Queenconf
    """
    def __init__(self):
        pass

 class Leaf_2:
    """
    Configuration class generated by Queenconf
    """
    def __init__(self):
        pass

 class Config:
    """
    Configuration class generated by Queenconf
    """
    def __init__(self):
        pass

    leaf_0: ClassVar[class] = Leaf_0()  # 
    leaf_1: ClassVar[class] = Leaf_1()  # 
    leaf_2: ClassVar[class] = Leaf_2()  # 
 
