from typing import ClassVar


class Queenconfig:

    """

    Configuration class generated by Queenconf

    """

    def __init__(self):

        self.config = Config()


class Extra:
    """
    Configuration class generated by Queenconf
    """
    def __init__(self):
        pass

 class Page:
    """
    Configuration class generated by Queenconf
    """
    def __init__(self):
        pass

    extra: ClassVar[class] = Extra()  # 
 class Config:
    """
    Configuration class generated by Queenconf
    """
    def __init__(self):
        pass

    page: ClassVar[class] = Page()  # 
 
