from typing import ClassVar


class Hazelconf:

    """

    Configuration class generated by Queenconf

    """

    def __init__(self):

        self.config = Config()


class Menu:
    def __init__(self):
        pass

class Config:
    def __init__(self):
        pass

    rowsPerPage: ClassVar[int] = 10
    showBlackFridayBanner: ClassVar[bool] = True
    showExtraHeader: ClassVar[bool] = False
    menu: ClassVar[class] = Menu()

